#!/usr/bin/env bash
# build-bootstrap.sh — regenerate spin-offline.sh, the fully-offline single-file
# installer (everything embedded). The `curl | bash` one-liner uses the tiny
# static launcher spin-bootstrap.sh instead — do NOT embed a payload there, it
# desyncs over a network pipe.
#
# This file embeds a gzipped tar of every tracked file as base64 after a
# self-extracting preamble. Run it whenever the kit changes; commit spin-offline.sh.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="spin-offline.sh"

command -v git >/dev/null || { echo "build needs git"; exit 1; }

# Tarball of tracked files, plus untracked source templates that may be present
# before the caller has staged a new maintenance lane or prompt example.
PAYLOAD="$(mktemp)"; trap 'rm -f "$PAYLOAD"' EXIT
{
  git ls-files -z -- ':!spin-offline.sh'
  git ls-files -z --others --exclude-standard -- 'org/ceo/*.example.md' 'org/projects/workspace/**'
} | tar --null -czf "$PAYLOAD" --files-from -

# Preamble: extracts the embedded payload. Intended for `bash spin-offline.sh`
# (download-and-run, no network). Has a git-clone fallback if somehow run without
# a readable file, but the supported piped path is the tiny spin-bootstrap.sh.
cat > "$OUT" <<'PREAMBLE'
#!/usr/bin/env bash
# spin-offline.sh — fully-offline self-extracting installer for SPIN.
#
#   Download then run:   bash spin-offline.sh [dest-dir]   # default ~/spin — no network/git needed
#
# Embeds the whole kit. For the `curl | bash` one-liner use spin-bootstrap.sh.
# Generated by scripts/build-bootstrap.sh — do not edit by hand.
set -euo pipefail
DEST="${1:-$HOME/spin}"
REPO="https://github.com/claudiaclawdbot/spin.git"
say(){ printf '\033[35m%s\033[0m\n' "$*"; }
b64d(){ base64 --decode 2>/dev/null || base64 -d 2>/dev/null || base64 -D; }

# NOTE: no heredocs below. When this script is piped (curl | bash) bash reads it
# from the same stream a heredoc would consume, which desyncs over a network and
# skips lines. printf never touches the stream, so it's pipe-safe.
printf '%s\n' \
'   ___ ___ ___ _  _' \
'  / __| _ \_ _| \| |   Super Pi Interoperable Navigator' \
'  \__ \  _/| || .` |   self-extracting installer' \
'  |___/_| |___|_|\_|'
say "→ installing to $DEST"

if [ -e "$DEST" ] && [ -n "$(ls -A "$DEST" 2>/dev/null || true)" ]; then
  echo "✗ $DEST exists and is not empty — pass a fresh dir: bash spin-offline.sh ~/somewhere-new"; exit 1
fi
mkdir -p "$DEST"

SELF="${BASH_SOURCE[0]:-$0}"
if [ -f "$SELF" ] && grep -qa '^__SPIN_PAYLOAD__$' "$SELF" 2>/dev/null; then
  say "extracting embedded payload…"
  line=$(awk '/^__SPIN_PAYLOAD__$/{print NR+1; exit}' "$SELF")
  tail -n +"$line" "$SELF" | b64d | tar xzf - -C "$DEST"
else
  command -v git >/dev/null || { echo "✗ no embedded payload found and git missing — re-download spin-offline.sh"; exit 1; }
  say "no embedded payload — git cloning $REPO…"
  tmp="$(mktemp -d)"; git clone --depth 1 "$REPO" "$tmp" >/dev/null 2>&1
  ( cd "$tmp" && git ls-files | tar czf - -T - ) | tar xzf - -C "$DEST"
  rm -rf "$tmp"
fi

cd "$DEST"
say "running install.sh…"
exec bash ./install.sh
__SPIN_PAYLOAD__
PREAMBLE

base64 < "$PAYLOAD" >> "$OUT"
chmod +x "$OUT"
echo "built $OUT — $(wc -c < "$OUT" | tr -d ' ') bytes, payload $(wc -c < "$PAYLOAD" | tr -d ' ') bytes"
