#!/usr/bin/env bash
# build-bootstrap.sh — regenerate spin-bootstrap.sh, the single-file installer.
#
# It embeds a gzipped tar of every tracked file (the whole kit minus the
# bootstrap itself) as base64 after a self-extracting bash preamble. Run this
# whenever the kit changes; commit the regenerated spin-bootstrap.sh.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="spin-bootstrap.sh"

command -v git >/dev/null || { echo "build needs git"; exit 1; }

# Tarball of tracked files (no spaces in our paths), minus the bootstrap output.
PAYLOAD="$(mktemp)"; trap 'rm -f "$PAYLOAD"' EXIT
git ls-files | grep -vx "$OUT" | tar czf "$PAYLOAD" -T -

# Preamble: extracts the embedded payload when run as a file; git-clones when piped.
cat > "$OUT" <<'PREAMBLE'
#!/usr/bin/env bash
# spin-bootstrap.sh — self-extracting installer for SPIN (Super Pi Interoperable Navigator).
#
#   Download then run:   bash spin-bootstrap.sh [dest-dir]        # default ~/spin — uses embedded payload
#   One-liner (piped):   curl -fsSL <url>/spin-bootstrap.sh | bash   # falls back to git clone
#
# Generated by scripts/build-bootstrap.sh — do not edit by hand.
set -euo pipefail
DEST="${1:-$HOME/spin}"
REPO="https://github.com/claudiaclawdbot/spin.git"
say(){ printf '\033[35m%s\033[0m\n' "$*"; }
b64d(){ base64 --decode 2>/dev/null || base64 -d 2>/dev/null || base64 -D; }

# NOTE: no heredocs below. When this script is piped (curl | bash) bash reads it
# from the same stream a heredoc would consume, which desyncs over a network and
# skips lines. printf never touches the stream, so it's pipe-safe.
printf '%s\n' \
'   ___ ___ ___ _  _' \
'  / __| _ \_ _| \| |   Super Pi Interoperable Navigator' \
'  \__ \  _/| || .` |   self-extracting installer' \
'  |___/_| |___|_|\_|'
say "→ installing to $DEST"

if [ -e "$DEST" ] && [ -n "$(ls -A "$DEST" 2>/dev/null || true)" ]; then
  echo "✗ $DEST exists and is not empty — pass a fresh dir: bash spin-bootstrap.sh ~/somewhere-new"; exit 1
fi
mkdir -p "$DEST"

SELF="${BASH_SOURCE[0]:-$0}"
if [ -f "$SELF" ] && grep -qa '^__SPIN_PAYLOAD__$' "$SELF" 2>/dev/null; then
  say "extracting embedded payload…"
  line=$(awk '/^__SPIN_PAYLOAD__$/{print NR+1; exit}' "$SELF")
  tail -n +"$line" "$SELF" | b64d | tar xzf - -C "$DEST"
else
  command -v git >/dev/null || { echo "✗ piped install needs git — or download spin-bootstrap.sh and run it"; exit 1; }
  say "no embedded payload (piped) — git cloning $REPO…"
  tmp="$(mktemp -d)"; git clone --depth 1 "$REPO" "$tmp" >/dev/null 2>&1
  ( cd "$tmp" && git ls-files | tar czf - -T - ) | tar xzf - -C "$DEST"
  rm -rf "$tmp"
fi

cd "$DEST"
say "running install.sh…"
exec bash ./install.sh
__SPIN_PAYLOAD__
PREAMBLE

base64 < "$PAYLOAD" >> "$OUT"
chmod +x "$OUT"
echo "built $OUT — $(wc -c < "$OUT" | tr -d ' ') bytes, payload $(wc -l < "$PAYLOAD" 2>/dev/null || echo '?') tar-bytes"
