#!/usr/bin/env bash
# wiki-update.sh — regenerates org/wiki/workspace.md from raw state files.
# Karpathy pattern: agents read the wiki, not the raw files. This script is the librarian.
#
# Run: bash scripts/wiki-update.sh
# Or:  add to workspace-status-watch.sh to keep it fresh automatically
#
# Reads:  org/state.json, org/AGENT_QUEUE.json, org/HUMAN_QUEUE.md, org/projects/*/FLOOR.md
# Writes: org/wiki/workspace.md (overwrites — it's generated, not hand-edited)

set -uo pipefail
ROOT="${OMP_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OUT="$ROOT/org/wiki/workspace.md"
TS="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

# ── helpers ─────────────────────────────────────────────────────────────────
floor_section() {  # $1=project-id $2=section-heading (e.g. "🔨 In progress")
  local f="$ROOT/org/projects/$1/FLOOR.md"
  [[ -f "$f" ]] || { echo "(no FLOOR.md)"; return; }
  # extract lines between ## $2 and the next ## heading
  awk "/^## $2/{found=1; next} found && /^## /{exit} found{print}" "$f" | grep -v '^$' | head -3
}

floor_now()      { floor_section "$1" "🔨 In progress"; }
floor_next()     { floor_section "$1" "⏭️ Next"; }
floor_waiting()  { floor_section "$1" "🚧 Waiting on human"; }

running_jobs() {
  local count=0
  local pf
  for pf in "$ROOT/org/jobs/"*.pid; do
    [[ -f "$pf" ]] || continue
    local pid; pid="$(cat "$pf" 2>/dev/null)"
    kill -0 "$pid" 2>/dev/null && (( count++ )) || true
  done
  echo "$count"
}

queued_jobs() {
  [[ -f "$ROOT/org/AGENT_QUEUE.json" ]] || { echo "0"; return; }
  node -e "
    const q = JSON.parse(require('fs').readFileSync('$ROOT/org/AGENT_QUEUE.json','utf8'));
    const jobs = Array.isArray(q) ? q : (q.jobs || []);
    console.log(jobs.filter(j=>j.status==='queued').length);
  " 2>/dev/null || echo "?"
}

human_items() {
  [[ -f "$ROOT/org/HUMAN_QUEUE.md" ]] || { echo "(none)"; return; }
  grep -E "^- " "$ROOT/org/HUMAN_QUEUE.md" | head -10 || echo "(none)"
}

# ── project status blocks ────────────────────────────────────────────────────
project_block() {  # $1=project-id
  local id="$1"
  local status; status="$(node -e "
    try {
      const s=JSON.parse(require('fs').readFileSync('$ROOT/org/state.json','utf8'));
      const p=s.project_orchestrators.find(x=>x.project==='$id')||{};
      console.log(p.status||'unknown');
    } catch(e){ console.log('unknown'); }
  " 2>/dev/null)"
  local now; now="$(floor_now "$id")"
  local next; next="$(floor_next "$id")"
  local wait; wait="$(floor_waiting "$id")"

  echo "### $id · $status"
  [[ -n "$now" ]]  && echo "- **Now:** $now"
  [[ -n "$next" ]] && echo "- **Next:** $next"
  [[ -n "$wait" ]] && echo "- **Waiting on human:** $wait"
  echo ""
}

# ── write the wiki ───────────────────────────────────────────────────────────
cat > "$OUT" <<WIKI
# Workspace Overview — auto-generated
<!-- Regenerated by scripts/wiki-update.sh every ~6s. DO NOT EDIT BY HAND. -->

_Last updated: ${TS}_

## Structure

\`\`\`
~/clawd/
├── projects/          ← all project code repos
│   ├── fidget-play/   ← DeFi spindle (Solidity/Foundry)
│   ├── built-by-ai/   ← web-dev agency (Next.js)
│   ├── agentclaudia/  ← newsletter automation (Node.js)
│   └── biible/        ← app (Next.js+Prisma)
├── org/               ← orchestration brain
│   ├── ceo/           ← CEO state, receipts
│   ├── projects/      ← per-project metadata (FLOOR.md, STATE.json, prompts)
│   ├── wiki/          ← THIS dir — read me, not raw files
│   ├── state.json     ← workspace truth
│   └── AGENT_QUEUE.json
└── scripts/           ← harness scripts
\`\`\`

## Live status

Running jobs: $(running_jobs)  |  Queued: $(queued_jobs)

## Projects

$(project_block fidget-play)
$(project_block built-by-ai)
$(project_block agentclaudia)
$(project_block biible)
## Waiting on human

$(human_items)

---
> **CEO:** read \`org/wiki/workspace.md\` (this file) for current state.
> Read raw files (\`state.json\`, \`AGENT_QUEUE.json\`, \`FLOOR.md\`) only when this doc is >10 min old
> or you need fine-grained detail. Per-project deep dives: \`org/wiki/projects/<id>.md\`.
WIKI

echo "wiki updated → $OUT ($TS)"
