#!/usr/bin/env bash
# Regenerate the workspace retrieval summary from live SPIN state.
set -uo pipefail

ROOT="${SPIN_ROOT:-${OMP_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}}"
OUT="$ROOT/org/wiki/workspace.md"
TS="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
mkdir -p "$(dirname "$OUT")"
TMP_OUT="$(mktemp "$OUT.tmp.XXXXXX")"
trap 'rm -f "$TMP_OUT"' EXIT

floor_section() {
  local file="$ROOT/org/projects/$1/FLOOR.md" wanted="$2"
  [[ -f "$file" ]] || return 0
  awk -v wanted="$wanted" '
    /^## / {
      heading=$0
      sub(/^##[[:space:]]+/, "", heading)
      if (found) exit
      found=(index(tolower(heading), tolower(wanted)) > 0)
      next
    }
    found && NF { print }
  ' "$file" | head -3
}

running_jobs() {
  local count=0 pid_file pid
  for pid_file in "$ROOT/org/jobs/"*.pid; do
    [[ -f "$pid_file" ]] || continue
    pid="$(cat "$pid_file" 2>/dev/null || true)"
    [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null && count=$((count + 1))
  done
  printf '%s\n' "$count"
}

queued_jobs() {
  node - "$ROOT/org/AGENT_QUEUE.json" <<'NODE' 2>/dev/null || printf '?\n'
const fs = require('fs');
try {
  const queue = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
  const jobs = Array.isArray(queue) ? queue : (queue.jobs || []);
  console.log(jobs.filter(job => job.status === 'queued').length);
} catch { console.log(0); }
NODE
}

human_items() {
  [[ -f "$ROOT/org/HUMAN_QUEUE.md" ]] || { printf '%s\n' '(none)'; return; }
  local items
  items="$(node "$ROOT/scripts/lib/human-queue-summary.js" "$ROOT" --lines 2>/dev/null | head -10 || true)"
  [[ -n "$items" ]] && printf '%s\n' "$items" || printf '%s\n' '(none)'
}

human_summary() {
  node "$ROOT/scripts/lib/human-queue-summary.js" "$ROOT" --text 2>/dev/null || printf '%s\n' 'nothing waiting'
}

project_ids() {
  node - "$ROOT/org/state.json" "$ROOT/org/OMP_HARNESS.json" <<'NODE'
const fs = require('fs');
const [stateFile, harnessFile] = process.argv.slice(2);
const ordered = [];
const seen = new Set();
const statuses = new Map();
const active = value => {
  const status = String(value || '').toLowerCase();
  return status && !/^(candidate|inactive|complete(?:d)?|archived|paused|disabled)(?:$|-)/.test(status);
};
const add = id => {
  if (id && !seen.has(id)) {
    seen.add(id);
    ordered.push(id);
  }
};
try {
  const state = JSON.parse(fs.readFileSync(stateFile, 'utf8'));
  for (const project of state.project_orchestrators || []) {
    const id = project.project || project.id;
    if (!id) continue;
    statuses.set(id, project.status || '');
    if (active(project.status)) add(id);
  }
} catch {}
try {
  const harness = JSON.parse(fs.readFileSync(harnessFile, 'utf8'));
  for (const [id, project] of Object.entries(harness.projects || {})) {
    const status = statuses.get(id);
    if (project && project.cmux_workspace && (!status || active(status))) add(id);
  }
} catch {}
for (const id of ordered) console.log(id);
NODE
}

project_status() {
  node - "$ROOT/org/state.json" "$1" <<'NODE' 2>/dev/null || printf '%s\n' unknown
const fs = require('fs');
const id = process.argv[3];
try {
  const state = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
  const project = (state.project_orchestrators || []).find(item => (item.project || item.id) === id) || {};
  console.log(project.status || 'unknown');
} catch { console.log('unknown'); }
NODE
}

project_block() {
  local id="$1" status now next waiting
  status="$(project_status "$id")"
  now="$(floor_section "$id" 'in progress')"
  next="$(floor_section "$id" 'next')"
  waiting="$(floor_section "$id" 'waiting')"
  printf '### %s - %s\n' "$id" "$status"
  [[ -n "$now" ]] && printf '%s\n' "- **Now:** $now"
  [[ -n "$next" ]] && printf '%s\n' "- **Next:** $next"
  [[ -n "$waiting" ]] && printf '%s\n' "- **Waiting on human:** $waiting"
  printf '\n'
}

PROJECT_BLOCKS=""
while IFS= read -r project_id; do
  [[ -n "$project_id" ]] || continue
  PROJECT_BLOCKS="${PROJECT_BLOCKS}$(project_block "$project_id")
"
done < <(project_ids)

cat > "$TMP_OUT" <<WIKI
# Workspace Overview - auto-generated
<!-- Regenerated by scripts/wiki-update.sh when portfolio state changes. DO NOT EDIT. -->

_Last content change: ${TS}_

## Structure

\`\`\`
SPIN runtime
|-- projects/          registered product-code links
|-- org/ceo/           Coordinator state, approvals, and receipts
|-- org/projects/      per-project floor state and prompts
|-- org/wiki/          generated retrieval indexes
|-- org/state.json     portfolio truth
|-- org/AGENT_QUEUE.json
\`-- scripts/           control-plane commands
\`\`\`

## Live status

Running jobs: $(running_jobs)  |  Queued: $(queued_jobs)

## Projects

${PROJECT_BLOCKS:-_(no active project floors)_}
## Waiting on human

$(human_summary)

$(human_items)

---
> **CEO:** read \`org/wiki/workspace.md\` for current portfolio context.
> Read raw \`state.json\`, \`AGENT_QUEUE.json\`, and \`FLOOR.md\` files when you
> need fine-grained evidence. Project indexes: \`org/wiki/projects/<id>.md\`.
WIKI

normalize_generated() {
  sed -E 's/^_Last content change: [^_]*_$/_Last content change: <dynamic>_/' "$1"
}

if [[ -f "$OUT" ]] && cmp -s <(normalize_generated "$OUT") <(normalize_generated "$TMP_OUT"); then
  exit 0
fi

mv "$TMP_OUT" "$OUT"
trap - EXIT
echo "wiki updated -> $OUT ($TS)"
